version: '3.8'

services:
  app:
    image: 869935063261.dkr.ecr.ap-northeast-2.amazonaws.com/fintech-app:latest
    container_name: easypay-app-prod
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: "deploy"
