services:
  app:
    image: 869935063261.dkr.ecr.ap-northeast-2.amazonaws.com/fintech-app:staging-latest
    container_name: easypay-app-staging
    ports:
      - "8091:8090"
    env_file:
      - .env.staging
    environment:
      SPRING_PROFILES_ACTIVE: "staging"
